---
language: ruby
cache: bundler
rvm:
  - '2.3.0'
env:
  matrix:
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v1.3   DB=postgres
    - SOLIDUS_BRANCH=v1.2   DB=postgres
    - SOLIDUS_BRANCH=v1.1   DB=postgres
    - SOLIDUS_BRANCH=v1.0   DB=postgres
    - SOLIDUS_BRANCH=master DB=mysql
    - SOLIDUS_BRANCH=v1.3   DB=mysql
    - SOLIDUS_BRANCH=v1.2   DB=mysql
    - SOLIDUS_BRANCH=v1.1   DB=mysql
    - SOLIDUS_BRANCH=v1.0   DB=mysql
sudo: false
before_script:
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
